[tool.pyright]
pythonVersion = "3.13"

typeCheckingMode = 'standard'

reportGeneralTypeIssues = false
reportUnusedImport = false
reportUndefinedVariable = false
reportImportCycles = false
reportPrivateUsage = false

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    "evn",
    ".env",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "venv",
    ".vscode",
    ".vs",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "__pycache__",
]


[tool.ruff]
output-format = "grouped"
line-length = 100
indent-width = 4

# NOTE: change this to your current version
# python 3.13
target-version = 'py313'

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    "evn",
    ".env",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "venv",
    ".vscode",
    ".vs",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "__pycache__",
]



[tool.ruff.lint]
select = [
    'E', 'W', 'F', 'I',
    'N', 'UP', 'B', 'C90',
    'C4', 'PL', 'TRY', 'ANN',
    'RUF', 'PERF', 'DJ', 'EXE',
    'PTH', 'SIM', 'RET', 'SLF',
    'NPY', 'FURB', 'ARG',
]

ignore = [
    'D105',
    'D106',
    # Ignore Django-specific docstring issues
    'D107',
    # Ignore magic value comparisons (common in Django ORM)
    'PLR2004',
]

fixable = ["ALL"]
unfixable = []


[tool.ruff.format]
quote-style = "double"

indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

docstring-code-format = true
docstring-code-line-length = "dynamic"

